; "Codewords for Coils of Hate"

<OBJECT CODEWORD-LARCENY
    (DESC "Larceny")
    (SYNONYM LARCENY)>

<OBJECT CODEWORD-LEVAD
    (DESC "Levad")
    (SYNONYM LEVAD)>

<OBJECT CODEWORD-MAZEL
    (DESC "Mazel")
    (SYNONYM MAZEL)>

<OBJECT CODEWORD-SATORI
    (DESC "Satori")
    (SYNONYM SATORI)>

<OBJECT CODEWORD-SHANK
    (DESC "Shank")
    (SYNONYM SHANK)>

<OBJECT CODEWORD-VENEFIX
    (DESC "Venefix")
    (SYNONYM VENEFIX)>
