"Coils of Hate (ZIL)"

<CONSTANT GAME-TITLE "||Coils of Hate">
<CONSTANT GAME-DESCRIPTION "|Mark Smith (1993)||Implemented in ZIL by SD Separa (2024)|">
<CONSTANT RELEASEID 2>
<CONSTANT IFID "E9645FAB-3F64-473C-AD76-C96D5F23868D">
<VERSION XZIP>

<INSERT-FILE "minilib">
<INSERT-FILE "story">

<ROUTINE GO ()
    <V-VERSION>
    <TELL CR "IFID: ">
    <TELL IFID>
    <CRLF>
    <GAME-BOOK>
    <QUIT-MSG>>
